# Generated by Django 5.2 on 2025-05-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='No bio provided', help_text='Tell us about yourself'),
        ),
    ]
