# Generated by Django 5.0.6 on 2025-05-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='profile_images/default.png', upload_to='profile_images/'),
        ),
    ]
