# Generated by Django 5.2 on 2025-05-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_userreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreport',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='userreport',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='reason',
            field=models.CharField(max_length=255),
        ),
    ]
