# Generated by Django 5.2 on 2025-05-06 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_rename_userreport_reportuser_reportcomment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportpost',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reportuser',
            name='reported_user',
        ),
        migrations.RemoveField(
            model_name='reportuser',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='reportuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='reason',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_on_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportuser',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_on_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
