# Generated by Django 5.2 on 2025-05-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_remove_reportuser_user_reportuser_reported_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportuser',
            name='reason',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
