# Generated by Django 5.2 on 2025-05-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_alter_reportuser_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportpost',
            name='reason',
            field=models.CharField(default='No reason provided', max_length=255),
        ),
        migrations.AlterField(
            model_name='reportuser',
            name='reason',
            field=models.CharField(default='No reason provided', max_length=255, null=True),
        ),
    ]
